### ISSUE TITLE
ssl异常

### ISSUE THREAD

**Issue by ikun-mr** [hmzz804/nonebot_plugin_cave#9]
**卧槽我怎么啥都没写上

**Comment by ikun-mr** [comment]
环境是py3.12.6，httpx==0.28，使用onebot v11协议，前端为llqqnt的llonebot，llonebot日志无报错
nonebot报错如下：
```python
12-05 20:14:52 [ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_cave, lineno=43) failed.
Traceback (most recent call last):
  File "C:\Python312\Lib\urllib\request.py", line 1344, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "C:\Python312\Lib\http\client.py", line 1336, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Python312\Lib\http\client.py", line 1382, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Python312\Lib\http\client.py", line 1331, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Python312\Lib\http\client.py", line 1091, in _send_output
    self.send(msg)
  File "C:\Python312\Lib\http\client.py", line 1035, in send
    self.connect()
  File "C:\Python312\Lib\http\client.py", line 1477, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "C:\Python312\Lib\ssl.py", line 455, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Python312\Lib\ssl.py", line 1041, in _create
    self.do_handshake()
  File "C:\Python312\Lib\ssl.py", line 1319, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1000)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 17, in <module>
  File "D:\bot\alhsk-bot\.venv\Lib\site-packages\nonebot\__init__.py", line 337, in run
    get_driver().run(*args, **kwargs)
  File "D:\bot\alhsk-bot\.venv\Lib\site-packages\nonebot\drivers\quart.py", line 169, in run
    uvicorn.run(
  File "D:\bot\alhsk-bot\.venv\Lib\site-packages\uvicorn\main.py", line 579, in run
    server.run()
  File "D:\bot\alhsk-bot\.venv\Lib\site-packages\uvicorn\server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Python312\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
  File "C:\Python312\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "C:\Python312\Lib\asyncio\base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "C:\Python312\Lib\asyncio\windows_events.py", line 322, in run_forever
    super().run_forever()
  File "C:\Python312\Lib\asyncio\base_events.py", line 641, in run_forever
    self._run_once()
  File "C:\Python312\Lib\asyncio\base_events.py", line 1986, in _run_once
    handle._run()
  File "C:\Python312\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "D:\bot\alhsk-bot\.venv\Lib\site-packages\nonebot\utils.py", line 254, in run_coro_with_shield
    return await coro
  File "D:\bot\alhsk-bot\.venv\Lib\site-packages\nonebot\message.py", line 506, in check_and_run_matcher
    await _run_matcher(
> File "D:\bot\alhsk-bot\.venv\Lib\site-packages\nonebot\message.py", line 458, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "D:\bot\alhsk-bot\.venv\Lib\site-packages\nonebot\internal\matcher\matcher.py", line 900, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "D:\bot\alhsk-bot\.venv\Lib\site-packages\nonebot\internal\matcher\matcher.py", line 837, in simple_run
    await handler(
  File "D:\bot\alhsk-bot\.venv\Lib\site-packages\nonebot\dependencies\__init__.py", line 113, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "D:\bot\alhsk-bot\.venv\Lib\site-packages\nonebot_plugin_cave\__init__.py", line 103, in cave_handle
    a_result = cave.add(message=a_message, contributor_id=user_id, state=1)
  File "D:\bot\alhsk-bot\.venv\Lib\site-packages\nonebot_plugin_cave\data_source.py", line 226, in add
    file_extension = self.get_url_extension(url=url)
  File "D:\bot\alhsk-bot\.venv\Lib\site-packages\nonebot_plugin_cave\data_source.py", line 162, in get_url_extension
    with urllib.request.urlopen(url=url) as response:
  File "C:\Python312\Lib\urllib\request.py", line 215, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python312\Lib\urllib\request.py", line 515, in open
    response = self._open(req, data)
  File "C:\Python312\Lib\urllib\request.py", line 532, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "C:\Python312\Lib\urllib\request.py", line 492, in _call_chain
    result = func(*args)
  File "C:\Python312\Lib\urllib\request.py", line 1392, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "C:\Python312\Lib\urllib\request.py", line 1347, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1000)>
```

**Comment by ikun-mr** [comment]
[nonebot_plugin_charpic@issue_3](https://github.com/1umine/nonebot_plugin_charpic/issues/3#issuecomment-2517334462)
这个的方案只能适用于这个插件，相同的环境在这就报错

**Comment by CN171-1** [comment]
> [nonebot_plugin_charpic@issue_3](https://github.com/1umine/nonebot_plugin_charpic/issues/3#issuecomment-2517334462) 这个的方案只能适用于这个插件，相同的环境在这就报错

因为cave插件在获取数据的时候使用的不是httpx库.png

**Comment by CN171-1** [comment]
> [nonebot_plugin_charpic@issue_3](https://github.com/1umine/nonebot_plugin_charpic/issues/3#issuecomment-2517334462) 这个的方案只能适用于这个插件，相同的环境在这就报错

且目前疑似问题出在获取图片扩展名上，修改该部分代码后不会报错，但会偶尔出现，当使用”回复消息”的方式添加回声洞时，提示”请[回复]添加的内容，或在-a后添加内容。“（实际上已[回复]了添加的内容），暂不清楚具体原因......
